"""
Learning from Demonstrations (LfD) training script.
Pre-trains the policy network using supervised learning on trajectories
generated by heuristic pruning methods.
"""

import os
import sys
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
import logging

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import config
from model.base_mllm import get_mllm
from pruner.rl_pruner import RLPruner
from pruner.random_pruner import RandomPruner
from data.base_loader import get_data_loader


class DemonstrationDataset(Dataset):
    """
    Dataset of pruning demonstrations (state-action pairs).
    """
    def __init__(self, demonstrations):
        """
        Args:
            demonstrations: list of dicts with keys:
                - 'visual_features': [num_tokens, hidden_dim]
                - 'query_embedding': [1, hidden_dim]
                - 'actions': [num_tokens] binary labels (1=keep, 0=prune)
        """
        self.demonstrations = demonstrations

    def __len__(self):
        return len(self.demonstrations)

    def __getitem__(self, idx):
        return self.demonstrations[idx]


def collate_demonstrations(batch):
    """
    Collate function for demonstration dataset.
    Pads sequences to same length within batch.
    """
    # Find max number of tokens in batch
    max_tokens = max(demo['visual_features'].shape[0] for demo in batch)

    batch_size = len(batch)
    hidden_dim = batch[0]['visual_features'].shape[1]

    # Initialize tensors
    visual_features = torch.zeros(batch_size, max_tokens, hidden_dim)
    query_embeddings = torch.stack([demo['query_embedding'] for demo in batch])
    actions = torch.zeros(batch_size, max_tokens)
    masks = torch.zeros(batch_size, max_tokens)  # Valid token mask

    # Fill tensors
    for i, demo in enumerate(batch):
        num_tokens = demo['visual_features'].shape[0]
        visual_features[i, :num_tokens, :] = demo['visual_features']
        actions[i, :num_tokens] = demo['actions']
        masks[i, :num_tokens] = 1.0

    return {
        'visual_features': visual_features,
        'query_embeddings': query_embeddings,
        'actions': actions,
        'masks': masks
    }


def generate_demonstrations(mllm, data_loader, heuristic_pruner, num_samples, num_steps=3):
    """
    Generate pruning demonstrations using a heuristic pruner.

    Args:
        mllm: vision-language model
        data_loader: data loader for samples
        heuristic_pruner: heuristic pruner (e.g., RandomPruner)
        num_samples: number of demonstrations to generate
        num_steps: number of pruning steps per trajectory
    Returns:
        demonstrations: list of demonstration dicts
    """
    demonstrations = []
    samples = data_loader.get_train_samples()

    print(f"Generating {num_samples} demonstrations with {num_steps} steps each...")

    for idx in tqdm(range(min(num_samples, len(samples)))):
        sample = samples[idx]

        try:
            # Get components from MLLM
            components = mllm.get_components_for_env(sample['image'], sample['question'])
            if components is None:
                continue

            visual_features = components['original_visual_features']  # [1, N, D]
            query_embedding = components['query_embeddings']  # [1, 1, D]

            # Generate multi-step trajectory
            current_features = visual_features.clone()

            for step in range(num_steps):
                # Calculate pruning ratio for this step
                # Progressively increase pruning: keep 80%, 60%, 40% etc.
                keep_ratio = 1.0 - (step + 1) * (0.2)
                keep_ratio = max(0.3, keep_ratio)  # Keep at least 30%

                # Get pruning scores from heuristic
                scores = heuristic_pruner.calculate_pruning_scores(
                    current_features,
                    query_embedding
                )  # [1, K]

                # Determine which tokens to keep
                num_tokens = scores.shape[1]
                num_to_keep = int(num_tokens * keep_ratio)
                num_to_keep = max(1, num_to_keep)

                # Get top-k indices
                _, top_indices = torch.topk(scores[0], num_to_keep, largest=True)

                # Create binary action labels
                actions = torch.zeros(num_tokens)
                actions[top_indices] = 1.0

                # Store demonstration
                demo = {
                    'visual_features': current_features[0].cpu(),  # [K, D]
                    'query_embedding': query_embedding[0].cpu(),  # [1, D]
                    'actions': actions.cpu()  # [K]
                }
                demonstrations.append(demo)

                # Update current features for next step
                current_features = current_features[:, top_indices, :]

        except Exception as e:
            print(f"Error generating demonstration {idx}: {e}")
            continue

    print(f"Generated {len(demonstrations)} demonstrations")
    return demonstrations


def train_lfd(agent, train_loader, optimizer, device, logger):
    """
    Train policy network using supervised learning on demonstrations.

    Args:
        agent: RLPruningAgent
        train_loader: DataLoader of demonstrations
        optimizer: optimizer
        device: device
        logger: logger
    Returns:
        avg_loss: average BCE loss
        avg_accuracy: average action prediction accuracy
    """
    agent.train()
    total_loss = 0.0
    total_accuracy = 0.0
    num_batches = 0

    criterion = nn.BCELoss(reduction='none')

    for batch in tqdm(train_loader, desc="Training"):
        visual_features = batch['visual_features'].to(device)
        query_embeddings = batch['query_embeddings'].to(device)
        actions = batch['actions'].to(device)
        masks = batch['masks'].to(device)

        # Forward pass
        probs = agent(visual_features, query_embeddings, return_value=False)  # [B, K]

        # Compute BCE loss (only on valid tokens)
        loss_per_token = criterion(probs, actions)  # [B, K]
        loss = (loss_per_token * masks).sum() / masks.sum()

        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(agent.parameters(), max_norm=1.0)
        optimizer.step()

        # Compute accuracy
        predicted_actions = (probs > 0.5).float()
        correct = ((predicted_actions == actions).float() * masks).sum()
        accuracy = correct / masks.sum()

        total_loss += loss.item()
        total_accuracy += accuracy.item()
        num_batches += 1

    avg_loss = total_loss / num_batches
    avg_accuracy = total_accuracy / num_batches

    return avg_loss, avg_accuracy


def main():
    """
    Main function for Learning from Demonstrations.
    """
    # Setup logger
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)
    handler = logging.StreamHandler()
    handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
    logger.addHandler(handler)

    logger.info("=== Learning from Demonstrations (LfD) ===")

    # Load MLLM
    logger.info("Loading MLLM...")
    mllm = get_mllm(config)

    # Load data
    logger.info("Loading data...")
    data_loader = get_data_loader(config)

    # Create heuristic pruner for generating demonstrations
    logger.info("Creating heuristic pruner...")
    heuristic_pruner = RandomPruner(mllm, config)

    # Generate demonstrations
    num_demos = getattr(config, 'LFD_NUM_DEMOS', 50000)
    num_steps = getattr(config, 'LFD_NUM_STEPS', 3)

    demo_path = os.path.join(config.LOG_DIR, 'demonstrations.pt')

    if os.path.exists(demo_path):
        logger.info(f"Loading demonstrations from {demo_path}")
        demonstrations = torch.load(demo_path)
    else:
        demonstrations = generate_demonstrations(
            mllm, data_loader, heuristic_pruner,
            num_samples=num_demos,
            num_steps=num_steps
        )
        torch.save(demonstrations, demo_path)
        logger.info(f"Saved demonstrations to {demo_path}")

    # Create dataset and dataloader
    demo_dataset = DemonstrationDataset(demonstrations)
    demo_loader = DataLoader(
        demo_dataset,
        batch_size=getattr(config, 'LFD_BATCH_SIZE', 128),
        shuffle=True,
        collate_fn=collate_demonstrations,
        num_workers=0
    )

    # Create RL agent
    logger.info("Creating RL agent...")
    rl_pruner = RLPruner(mllm, config)
    agent = rl_pruner.model

    # Setup optimizer
    lr = getattr(config, 'LFD_LEARNING_RATE', 5e-5)
    optimizer = optim.AdamW(agent.parameters(), lr=lr, weight_decay=0.01)

    # Training loop
    num_epochs = getattr(config, 'LFD_NUM_EPOCHS', 5)
    logger.info(f"Training for {num_epochs} epochs...")

    for epoch in range(num_epochs):
        avg_loss, avg_accuracy = train_lfd(agent, demo_loader, optimizer, config.DEVICE, logger)

        logger.info(f"Epoch {epoch+1}/{num_epochs} - Loss: {avg_loss:.4f}, Accuracy: {avg_accuracy:.4f}")

        # Save checkpoint
        checkpoint_path = os.path.join(config.LOG_DIR, f'lfd_checkpoint_epoch{epoch+1}.pt')
        torch.save({
            'epoch': epoch,
            'model_state_dict': agent.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': avg_loss,
            'accuracy': avg_accuracy
        }, checkpoint_path)
        logger.info(f"Saved checkpoint to {checkpoint_path}")

    logger.info("LfD training completed!")


if __name__ == "__main__":
    main()
